package com.example.bloodsync_android.util

import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage(val code: String, val englishName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    HINDI("hi", "Hindi", "हिंदी"),
    GUJARATI("gu", "Gujarati", "ગુજરાતી")
}

data class TranslationStrings(
    // Common & Navigation
    val appName: String,
    val home: String,
    val donors: String,
    val appointments: String,
    val health: String,
    val profile: String,
    val settings: String,
    val notifications: String,
    val back: String,
    val close: String,
    val cancel: String,
    val confirm: String,
    val saveChanges: String,
    val signOut: String,

    // Bottom Navigation Specific
    val navHome: String,
    val navHistory: String,
    val navSafety: String,
    val navBook: String,
    val navProfile: String,

    // Home Screen
    val needBloodUrgently: String,
    val broadcastSosDesc: String,
    val requestBloodSos: String,
    val quickServices: String,
    val findDonorsTitle: String,
    val findDonorsDesc: String,
    val bloodBanksTitle: String,
    val bloodBanksDesc: String,
    val bookSlotTitle: String,
    val bookSlotDesc: String,
    val eligibleNow: String,
    val recoveryActive: String,
    val activeSosAlerts: String,
    val certifiedBloodBanks: String,
    val emergencyCall: String,
    val donorNetworkSubtitle: String,

    // Auth Screen
    val signIn: String,
    val registerDonor: String,
    val continueWithGoogle: String,
    val fullName: String,
    val emailAddress: String,
    val phoneNumber: String,
    val cityRegion: String,
    val password: String,
    val selectBloodGroup: String,
    val volunteerForEmergency: String,
    val createDonorAccount: String,
    val signInToBloodSync: String,
    val invalidEmailError: String,
    val invalidPhoneError: String,
    val invalidNameError: String,
    val passwordMinLengthError: String,

    // Gender & Age & Restrictions
    val gender: String,
    val genderMale: String,
    val genderFemale: String,
    val age: String,
    val agePlaceholder: String,
    val minAgeHint: String,
    val ageRestrictionError: String,
    val invalidAgeError: String,

    // Language Dialog
    val chooseYourLanguage: String,
    val selectLanguageSubtitle: String,
    val continueButton: String,
    val englishLabel: String,
    val hindiLabel: String,
    val gujaratiLabel: String,

    // Donors Directory
    val donorsDirectoryTitle: String,
    val searchDonorsPlaceholder: String,
    val allBloodGroups: String,
    val noDonorsFound: String,
    val beTheFirstDonor: String,
    val chatOnWhatsApp: String,
    val callDonor: String,
    val availableNow: String,
    val busyDonor: String,

    // Settings Screen
    val settingsTitle: String,
    val appearanceSection: String,
    val lightMode: String,
    val darkMode: String,
    val systemMode: String,
    val languageSection: String,
    val notificationSection: String,
    val emergencyAlerts: String,
    val appointmentReminders: String,
    val clinicalSafetySection: String,
    val dataManagementSection: String,
    val clearCacheButton: String,
    val appVersion: String,

    // Profile Screen
    val donorProfileTitle: String,
    val editProfile: String,
    val totalDonations: String,
    val livesSaved: String,
    val recoveryStatus: String,
    val eligibleStatus: String,
    val waitingDays: String,
    val personalContactInfo: String,
    val availabilityNotifications: String,
    val bloodDonated: String,
    val availableForDonations: String,
    val profileUpdatedSuccess: String,

    // Exit Dialog
    val exitAppTitle: String,
    val exitAppMessage: String,
    val yesExit: String,
    val noStay: String,

    // Notifications & Alerts
    val newDonorRegisteredTitle: String,
    val newDonorRegisteredBody: String
)

val EnglishTranslations = TranslationStrings(
    appName = "BloodSync",
    home = "Home",
    donors = "Donors",
    appointments = "Appointments",
    health = "Health",
    profile = "Profile",
    settings = "Settings",
    notifications = "Notifications",
    back = "Back",
    close = "Close",
    cancel = "Cancel",
    confirm = "Confirm",
    saveChanges = "Save Changes",
    signOut = "Sign Out",

    navHome = "Home",
    navHistory = "History",
    navSafety = "Safety",
    navBook = "Book",
    navProfile = "Profile",

    needBloodUrgently = "Need Blood Urgently?",
    broadcastSosDesc = "Broadcast an instant emergency SOS to all matching voluntary donors nearby.",
    requestBloodSos = "REQUEST BLOOD (1-TAP SOS)",
    quickServices = "Quick Services",
    findDonorsTitle = "Find Donors",
    findDonorsDesc = "Direct verified donors directory",
    bloodBanksTitle = "Blood Banks",
    bloodBanksDesc = "Real-time hospital reserves",
    bookSlotTitle = "Book Slot",
    bookSlotDesc = "Scheduled clinic donation",
    eligibleNow = "Eligible Now",
    recoveryActive = "Days Recovery Left",
    activeSosAlerts = "Active Emergency SOS Alerts",
    certifiedBloodBanks = "Certified Regional Blood Banks",
    emergencyCall = "Emergency Hotline (108)",
    donorNetworkSubtitle = "Fast, reliable real-time blood donor network",

    signIn = "Sign In",
    registerDonor = "Register Donor",
    continueWithGoogle = "Continue with Google",
    fullName = "Full Name",
    emailAddress = "Email Address",
    phoneNumber = "Mobile Phone Number",
    cityRegion = "City / Region",
    password = "Password",
    selectBloodGroup = "Select Blood Group",
    volunteerForEmergency = "Volunteer for 24/7 emergency blood requests nearby",
    createDonorAccount = "Create Donor Account",
    signInToBloodSync = "Sign In to BloodSync",
    invalidEmailError = "Invalid email format! Please include a valid extension (e.g., name@gmail.com).",
    invalidPhoneError = "Invalid phone number! Must be a 10-digit number.",
    invalidNameError = "Please enter your full name (minimum 2 letters).",
    passwordMinLengthError = "Password must be at least 6 characters.",

    gender = "Gender",
    genderMale = "Male",
    genderFemale = "Female",
    age = "Age (Years)",
    agePlaceholder = "e.g. 18",
    minAgeHint = "Minimum registration age: 15 years",
    ageRestrictionError = "⚠️ Age Restriction: Minimum age required to register is 15 years old. You cannot register if you are under 15.",
    invalidAgeError = "Please enter a valid age (15 - 100 years).",

    chooseYourLanguage = "Choose Your Language",
    selectLanguageSubtitle = "Select your preferred language for BloodSync",
    continueButton = "Continue",
    englishLabel = "English",
    hindiLabel = "हिंदी (Hindi)",
    gujaratiLabel = "ગુજરાતી (Gujarati)",

    donorsDirectoryTitle = "Voluntary Donors Directory",
    searchDonorsPlaceholder = "Search donors by name, city, or blood group...",
    allBloodGroups = "All Groups",
    noDonorsFound = "No voluntary donors found",
    beTheFirstDonor = "Be the first lifesaver to register in your area!",
    chatOnWhatsApp = "WhatsApp Chat",
    callDonor = "Call Donor",
    availableNow = "Available Now",
    busyDonor = "Currently Busy",

    settingsTitle = "Settings",
    appearanceSection = "Appearance & Theme",
    lightMode = "Light Mode",
    darkMode = "Dark Mode",
    systemMode = "System Mode",
    languageSection = "App Language / भाषा / ભાષા",
    notificationSection = "Notification Controls",
    emergencyAlerts = "Emergency Blood Broadcasts",
    appointmentReminders = "Donation Reminders & Milestones",
    clinicalSafetySection = "Clinical Safety",
    dataManagementSection = "Data Management",
    clearCacheButton = "Clear Local Cache & Reset",
    appVersion = "BloodSync v2.3.0 • Production Build",

    donorProfileTitle = "Donor Profile",
    editProfile = "Edit Profile",
    totalDonations = "Donations",
    livesSaved = "Lives Saved",
    recoveryStatus = "Recovery",
    eligibleStatus = "Eligible",
    waitingDays = "Days Left",
    personalContactInfo = "Personal & Contact Information",
    availabilityNotifications = "Donor Availability & Alerts",
    bloodDonated = "Donated",
    availableForDonations = "Available for Emergency Donations",
    profileUpdatedSuccess = "Profile updated successfully!",

    exitAppTitle = "Exit BloodSync?",
    exitAppMessage = "Are you sure you want to close the app? You can stay to receive live blood donation and emergency alerts.",
    yesExit = "Yes, Exit",
    noStay = "No, Stay",

    newDonorRegisteredTitle = "🚨 New Donor Registered!",
    newDonorRegisteredBody = "has registered as an active voluntary donor."
)

val HindiTranslations = TranslationStrings(
    appName = "ब्लडसिंक (BloodSync)",
    home = "होम",
    donors = "रक्तदाता",
    appointments = "अपॉइंटमेंट",
    health = "सुरक्षा",
    profile = "प्रोफाइल",
    settings = "सेटिंग्स",
    notifications = "सूचनाएं",
    back = "वापस",
    close = "बंद करें",
    cancel = "रद्द करें",
    confirm = "पुष्टि करें",
    saveChanges = "बदलाव सहेजें",
    signOut = "लॉग आउट",

    navHome = "होम",
    navHistory = "इतिहास",
    navSafety = "सुरक्षा",
    navBook = "बुक",
    navProfile = "प्रोफाइल",

    needBloodUrgently = "क्या तुरंत रक्त की आवश्यकता है?",
    broadcastSosDesc = "आस-पास के सभी योग्य स्वैच्छिक रक्तदाताओं को तुरंत आपातकालीन SOS संदेश भेजें।",
    requestBloodSos = "रक्त अनुरोध करें (1-टैप SOS)",
    quickServices = "त्वरित सेवाएं",
    findDonorsTitle = "रक्तदाता खोजें",
    findDonorsDesc = "सत्यापित रक्तदाता सूची",
    bloodBanksTitle = "ब्लड बैंक",
    bloodBanksDesc = "अस्पताल व ब्लड बैंक स्टॉक",
    bookSlotTitle = "स्लॉट बुक करें",
    bookSlotDesc = "रक्तदान के लिए समय चुनें",
    eligibleNow = "रक्तदान के लिए योग्य",
    recoveryActive = "दिन रिकवरी बाकी",
    activeSosAlerts = "सक्रिय आपातकालीन SOS अलर्ट",
    certifiedBloodBanks = "प्रमाणित क्षेत्रीय ब्लड बैंक",
    emergencyCall = "आपातकालीन हेल्पलाइन (108)",
    donorNetworkSubtitle = "तेज, विश्वसनीय 24/7 स्वैच्छिक रक्तदाता नेटवर्क",

    signIn = "साइन इन",
    registerDonor = "रक्तदाता पंजीकरण",
    continueWithGoogle = "Google के साथ जारी रखें",
    fullName = "पूरा नाम",
    emailAddress = "ईमेल पता",
    phoneNumber = "मोबाइल फोन नंबर",
    cityRegion = "शहर / क्षेत्र",
    password = "पासवर्ड",
    selectBloodGroup = "रक्त समूह चुनें",
    volunteerForEmergency = "24/7 आपातकालीन रक्तदान अनुरोधों के लिए स्वेच्छा से जुड़ें",
    createDonorAccount = "रक्तदाता खाता बनाएं",
    signInToBloodSync = "BloodSync में साइन इन करें",
    invalidEmailError = "अमान्य ईमेल! कृपया सही एक्सटेंशन के साथ ईमेल दर्ज करें (उदा. name@gmail.com)।",
    invalidPhoneError = "अमान्य फोन नंबर! 10 अंकों का मान्य मोबाइल नंबर दर्ज करें।",
    invalidNameError = "कृपया अपना पूरा नाम दर्ज करें (कम से कम 2 अक्षर)।",
    passwordMinLengthError = "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",

    gender = "लिंग (Gender)",
    genderMale = "पुरुष (Male)",
    genderFemale = "महिला (Female)",
    age = "आयु (वर्ष)",
    agePlaceholder = "उदा. 18",
    minAgeHint = "पंजीकरण के लिए न्यूनतम आयु: 15 वर्ष",
    ageRestrictionError = "⚠️ आयु प्रतिबंध: पंजीकरण के लिए न्यूनतम आयु 15 वर्ष होनी चाहिए। 15 वर्ष से कम आयु वाले पंजीकरण नहीं कर सकते।",
    invalidAgeError = "कृपया 15 से 100 वर्ष के बीच मान्य आयु दर्ज करें।",

    chooseYourLanguage = "अपनी भाषा चुनें",
    selectLanguageSubtitle = "BloodSync ऐप के लिए अपनी पसंदीदा भाषा का चयन करें",
    continueButton = "आगे बढ़ें",
    englishLabel = "English (अंग्रेज़ी)",
    hindiLabel = "हिंदी (Hindi)",
    gujaratiLabel = "ગુજરાતી (Gujarati)",

    donorsDirectoryTitle = "स्वैच्छिक रक्तदाता निर्देशिका",
    searchDonorsPlaceholder = "नाम, शहर या रक्त समूह से खोजें...",
    allBloodGroups = "सभी ग्रुप",
    noDonorsFound = "कोई पंजीकृत रक्तदाता नहीं मिला",
    beTheFirstDonor = "अपने क्षेत्र में जीवन रक्षक बनने वाले पहले रक्तदाता बनें!",
    chatOnWhatsApp = "व्हाट्सएप चैट",
    callDonor = "कॉल करें",
    availableNow = "उपलब्ध",
    busyDonor = "वर्तमान में व्यस्त",

    settingsTitle = "सेटिंग्स",
    appearanceSection = "दिखावट और थीम",
    lightMode = "लाइट मोड",
    darkMode = "डार्क मोड",
    systemMode = "सिस्टम मोड",
    languageSection = "ऐप भाषा (Language / भाषा / ભાષા)",
    notificationSection = "सूचना नियंत्रण",
    emergencyAlerts = "आपातकालीन रक्त प्रसारण",
    appointmentReminders = "रक्तदान रिमाइंडर और माइलस्टोन",
    clinicalSafetySection = "चिकित्सीय सुरक्षा (WHO 90-दिन)",
    dataManagementSection = "डेटा प्रबंधन",
    clearCacheButton = "लोकल कैश साफ़ करें और रीसेट करें",
    appVersion = "BloodSync v2.3.0 • सुरक्षित संस्करण",

    donorProfileTitle = "रक्तदाता प्रोफाइल",
    editProfile = "प्रोफाइल संपादित करें",
    totalDonations = "कुल रक्तदान",
    livesSaved = "बचाए गए जीवन",
    recoveryStatus = "रिकवरी",
    eligibleStatus = "योग्य",
    waitingDays = "दिन शेष",
    personalContactInfo = "व्यक्तिगत और संपर्क जानकारी",
    availabilityNotifications = "रक्तदाता उपलब्धता और अलर्ट",
    bloodDonated = "रक्तदान किया",
    availableForDonations = "आपातकालीन रक्तदान के लिए उपलब्ध",
    profileUpdatedSuccess = "प्रोफाइल सफलतापूर्वक अपडेट हो गई!",

    exitAppTitle = "BloodSync से बाहर निकलें?",
    exitAppMessage = "क्या आप वाकई ऐप बंद करना चाहते हैं? आप आपातकालीन रक्तदान अलर्ट प्राप्त करने के लिए ऐप में बने रह सकते हैं।",
    yesExit = "हाँ, बाहर निकलें",
    noStay = "नहीं, यहीं रहें",

    newDonorRegisteredTitle = "🚨 नया रक्तदाता पंजीकृत हुआ!",
    newDonorRegisteredBody = "एक सक्रिय स्वैच्छिक रक्तदाता के रूप में पंजीकृत हुए हैं।"
)

val GujaratiTranslations = TranslationStrings(
    appName = "બ્લડસિંક (BloodSync)",
    home = "હોમ",
    donors = "દાતાઓ",
    appointments = "મુલાકાત",
    health = "સુરક્ષા",
    profile = "પ્રોફાઇલ",
    settings = "સેટિંગ્સ",
    notifications = "સૂચનાઓ",
    back = "પાછળ",
    close = "બંધ કરો",
    cancel = "રદ કરો",
    confirm = "પુષ્ટિ કરો",
    saveChanges = "ફેરફારો સાચવો",
    signOut = "લૉગ આઉટ",

    navHome = "હોમ",
    navHistory = "ઇતિહાસ",
    navSafety = "સુરક્ષા",
    navBook = "બુકિંગ",
    navProfile = "પ્રોફાઇલ",

    needBloodUrgently = "શું તાત્કાલિક લોહીની જરૂર છે?",
    broadcastSosDesc = "નજીકના તમામ સુસંગત સ્વૈચ્છિક રક્તદાતાઓને તાત્કાલિક કટોકટી SOS સંદેશ મોકલો.",
    requestBloodSos = "લોહીની વિનંતી કરો (1-ટેપ SOS)",
    quickServices = "ઝડપી સેવાઓ",
    findDonorsTitle = "દાતાઓ શોધો",
    findDonorsDesc = "ચકાસાયેલ રક્તદાતાઓની યાદી",
    bloodBanksTitle = "બ્લડ બેંકો",
    bloodBanksDesc = "હોસ્પિટલ અને બ્લડ બેંક સ્ટોક",
    bookSlotTitle = "સ્લોટ બુક કરો",
    bookSlotDesc = "રક્તદાન માટે સમય પસંદ કરો",
    eligibleNow = "રક્તદાન માટે યોગ્ય",
    recoveryActive = "દિવસ રિકવરી બાકી",
    activeSosAlerts = "સક્રિય કટોકટી SOS ચેતવણીઓ",
    certifiedBloodBanks = "પ્રમાણિત પ્રાદેશિક બ્લડ બેંકો",
    emergencyCall = "કટોકટી હેલ્પલાઇન (108)",
    donorNetworkSubtitle = "ઝડપી, વિશ્વસનીય 24/7 સ્વૈચ્છિક રક્તદાતા નેટવર્ક",

    signIn = "સાઇન ઇન",
    registerDonor = "દાતા નોંધણી",
    continueWithGoogle = "Google સાથે ચાલુ રાખો",
    fullName = "પૂરું નામ",
    emailAddress = "ઇમેઇલ સરનામું",
    phoneNumber = "મોબાઇલ ફોન નંબર",
    cityRegion = "શહેર / વિસ્તાર",
    password = "પાસવર્ડ",
    selectBloodGroup = "બ્લડ ગ્રૂપ પસંદ કરો",
    volunteerForEmergency = "24/7 કટોકટી રક્તદાન વિનંતીઓ માટે સ્વેચ્છાએ જોડાઓ",
    createDonorAccount = "દાતા એકાઉન્ટ બનાવો",
    signInToBloodSync = "BloodSync માં સાઇન ઇન કરો",
    invalidEmailError = "અમાન્ય ઇમેઇલ! કૃપા કરીને માન્ય એક્સ્ટેંશન સાથે ઇમેઇલ દાખલ કરો (દા.ત. name@gmail.com).",
    invalidPhoneError = "અમાન્ય ફોન નંબર! 10 અંકનો માન્ય મોબાઇલ નંબર દાખલ કરો.",
    invalidNameError = "કૃપા કરીને તમારું પૂરું નામ દાખલ કરો (ઓછામાં ઓછા 2 અક્ષરો).",
    passwordMinLengthError = "પાસવર્ડ ઓછામાં ઓછો 6 અક્ષરોનો હોવો જોઈએ.",

    gender = "જાતિ (Gender)",
    genderMale = "પુરુષ (Male)",
    genderFemale = "સ્ત્રી (Female)",
    age = "ઉંમર (વર્ષ)",
    agePlaceholder = "દા.ત. 18",
    minAgeHint = "નોંધણી માટે લઘુત્તમ ઉંમર: 15 વર્ષ",
    ageRestrictionError = "⚠️ ઉંમર મર્યાદા: રક્તદાતા નોંધણી માટે લઘુત્તમ ઉંમર 15 વર્ષ હોવી જરૂરી છે. 15 વર્ષથી ઓછી ઉંમરના વપરાશકર્તાઓ નોંધણી કરી શકતા નથી.",
    invalidAgeError = "કૃપા કરીને 15 થી 100 વર્ષ વચ્ચે માન્ય ઉંમર દાખલ કરો.",

    chooseYourLanguage = "તમારી ભાષા પસંદ કરો",
    selectLanguageSubtitle = "BloodSync એપ્લિકેશન માટે તમારી પસંદગીની ભાષા પસંદ કરો",
    continueButton = "આગળ વધો",
    englishLabel = "English (અંગ્રેજી)",
    hindiLabel = "हिंदी (હિન્દી)",
    gujaratiLabel = "ગુજરાતી (Gujarati)",

    donorsDirectoryTitle = "સ્વૈચ્છિક રક્તદાતાઓની યાદી",
    searchDonorsPlaceholder = "નામ, શહેર અથવા બ્લડ ગ્રૂપથી શોધો...",
    allBloodGroups = "બધા ગ્રૂપ",
    noDonorsFound = "કોઈ નોંધાયેલા રક્તદાતા મળ્યા નથી",
    beTheFirstDonor = "તમારા વિસ્તારમાં જીવનદાતા બનનાર પ્રથમ રક્તદાતા બનો!",
    chatOnWhatsApp = "WhatsApp ચેટ",
    callDonor = "કૉલ કરો",
    availableNow = "ઉપલબ્ધ",
    busyDonor = "હાલમાં વ્યસ્ત",

    settingsTitle = "સેટિંગ્સ",
    appearanceSection = "દેખાવ અને થીમ",
    lightMode = "લાઇટ મોડ",
    darkMode = "ડાર્ક મોડ",
    systemMode = "સિસ્ટમ મોડ",
    languageSection = "એપ્લિકેશન ભાષા (Language / भाषा / ભાષા)",
    notificationSection = "સૂચના નિયંત્રણો",
    emergencyAlerts = "કટોકટી રક્ત પ્રસારણ",
    appointmentReminders = "રક્તદાન રીમાઇન્ડર અને પ્રમાણપત્ર",
    clinicalSafetySection = "તબીબી સલામતી (WHO 90-દિવસ)",
    dataManagementSection = "ડેટા મેનેજમેન્ટ",
    clearCacheButton = "લોકલ કેશ સાફ કરો અને રીસેટ કરો",
    appVersion = "BloodSync v2.3.0 • ઉત્પાદન સંસ્કરણ",

    donorProfileTitle = "દાતા પ્રોફાઇલ",
    editProfile = "પ્રોફાઇલ સંપાદિત કરો",
    totalDonations = "કુલ રક્તદાન",
    livesSaved = "બચાવેલ જીવન",
    recoveryStatus = "રિકવરી",
    eligibleStatus = "યોગ્ય",
    waitingDays = "દિવસ બાકી",
    personalContactInfo = "વ્યક્તિગત અને સંપર્ક માહિતી",
    availabilityNotifications = "દાતા ઉપલબ્ધતા અને સૂચનાઓ",
    bloodDonated = "દાન કર્યું",
    availableForDonations = "કટોકટી રક્તદાન માટે ઉપલબ્ધ",
    profileUpdatedSuccess = "પ્રોફાઇલ સફળતાપૂર્વક અપડેટ થઈ ગઈ!",

    exitAppTitle = "BloodSync બંધ કરવું છે?",
    exitAppMessage = "શું તમે ખરેખર એપ બંધ કરવા માંગો છો? કટોકટી રક્તદાન એલર્ટ મેળવવા માટે તમે એપમાં રહી શકો છો.",
    yesExit = "હા, બહાર નીકળો",
    noStay = "ના, રોકાઓ",

    newDonorRegisteredTitle = "🚨 નવો રક્તદાતા નોંધાયો!",
    newDonorRegisteredBody = "એક સક્રિય સ્વૈચ્છિક રક્તદાતા તરીકે નોંધાયા છે."
)

val LocalAppStrings = staticCompositionLocalOf<TranslationStrings> { EnglishTranslations }
val LocalAppLanguage = staticCompositionLocalOf<AppLanguage> { AppLanguage.ENGLISH }

object LanguageManager {
    fun getStrings(language: AppLanguage): TranslationStrings = when (language) {
        AppLanguage.ENGLISH -> EnglishTranslations
        AppLanguage.HINDI -> HindiTranslations
        AppLanguage.GUJARATI -> GujaratiTranslations
    }
}
