package com.example.bloodsync_android.util

import androidx.compose.runtime.staticCompositionLocalOf

data class TranslationStrings(
    // Common & Navigation
    val appName: String,
    val home: String,
    val donors: String,
    val appointments: String,
    val health: String,
    val profile: String,
    val settings: String,
    val notifications: String,
    val back: String,
    val close: String,
    val cancel: String,
    val confirm: String,
    val saveChanges: String,
    val signOut: String,

    // Bottom Navigation Specific
    val navHome: String,
    val navHistory: String,
    val navSafety: String,
    val navBook: String,
    val navProfile: String,

    // Home Screen
    val needBloodUrgently: String,
    val broadcastSosDesc: String,
    val requestBloodSos: String,
    val quickServices: String,
    val findDonorsTitle: String,
    val findDonorsDesc: String,
    val bloodBanksTitle: String,
    val bloodBanksDesc: String,
    val bookSlotTitle: String,
    val bookSlotDesc: String,
    val eligibleNow: String,
    val recoveryActive: String,
    val activeSosAlerts: String,
    val certifiedBloodBanks: String,
    val emergencyCall: String,
    val donorNetworkSubtitle: String,

    // Auth Screen
    val signIn: String,
    val registerDonor: String,
    val continueWithGoogle: String,
    val fullName: String,
    val emailAddress: String,
    val phoneNumber: String,
    val cityRegion: String,
    val password: String,
    val selectBloodGroup: String,
    val volunteerForEmergency: String,
    val createDonorAccount: String,
    val signInToBloodSync: String,
    val invalidEmailError: String,
    val invalidPhoneError: String,
    val invalidNameError: String,
    val passwordMinLengthError: String,

    // Gender & Age & Restrictions
    val gender: String,
    val genderMale: String,
    val genderFemale: String,
    val age: String,
    val agePlaceholder: String,
    val minAgeHint: String,
    val ageRestrictionError: String,
    val invalidAgeError: String,

    // Language Dialog
    val chooseYourLanguage: String,
    val selectLanguageSubtitle: String,
    val continueButton: String,
    val englishLabel: String,
    val hindiLabel: String,
    val gujaratiLabel: String,

    // Donors Directory
    val donorsDirectoryTitle: String,
    val searchDonorsPlaceholder: String,
    val allBloodGroups: String,
    val noDonorsFound: String,
    val beTheFirstDonor: String,
    val chatOnWhatsApp: String,
    val callDonor: String,
    val availableNow: String,
    val busyDonor: String,

    // Settings Screen
    val settingsTitle: String,
    val appearanceSection: String,
    val lightMode: String,
    val darkMode: String,
    val systemMode: String,
    val languageSection: String,
    val notificationSection: String,
    val emergencyAlerts: String,
    val appointmentReminders: String,
    val clinicalSafetySection: String,
    val dataManagementSection: String,
    val clearCacheButton: String,
    val appVersion: String,

    // Profile Screen
    val donorProfileTitle: String,
    val editProfile: String,
    val totalDonations: String,
    val livesSaved: String,
    val recoveryStatus: String,
    val eligibleStatus: String,
    val waitingDays: String,
    val personalContactInfo: String,
    val availabilityNotifications: String,
    val bloodDonated: String,
    val availableForDonations: String,
    val profileUpdatedSuccess: String,

    // Exit Dialog
    val exitAppTitle: String,
    val exitAppMessage: String,
    val yesExit: String,
    val noStay: String,

    // Notifications & Alerts
    val newDonorRegisteredTitle: String,
    val newDonorRegisteredBody: String
)

val EnglishTranslations = TranslationStrings(
    appName = "BloodSync",
    home = "Home",
    donors = "Donors",
    appointments = "Appointments",
    health = "Health",
    profile = "Profile",
    settings = "Settings",
    notifications = "Notifications",
    back = "Back",
    close = "Close",
    cancel = "Cancel",
    confirm = "Confirm",
    saveChanges = "Save Changes",
    signOut = "Sign Out",

    navHome = "Home",
    navHistory = "History",
    navSafety = "Safety",
    navBook = "Book",
    navProfile = "Profile",

    needBloodUrgently = "Need Blood Urgently?",
    broadcastSosDesc = "Broadcast an instant emergency SOS to all matching voluntary donors nearby.",
    requestBloodSos = "REQUEST BLOOD (1-TAP SOS)",
    quickServices = "Quick Services",
    findDonorsTitle = "Find Donors",
    findDonorsDesc = "Direct verified donors directory",
    bloodBanksTitle = "Blood Banks",
    bloodBanksDesc = "Real-time hospital reserves",
    bookSlotTitle = "Book Slot",
    bookSlotDesc = "Scheduled clinic donation",
    eligibleNow = "Eligible Now",
    recoveryActive = "Days Recovery Left",
    activeSosAlerts = "Active Emergency SOS Alerts",
    certifiedBloodBanks = "Certified Regional Blood Banks",
    emergencyCall = "Emergency Hotline (108)",
    donorNetworkSubtitle = "Fast, reliable real-time blood donor network",

    signIn = "Sign In",
    registerDonor = "Register Donor",
    continueWithGoogle = "Continue with Google",
    fullName = "Full Name",
    emailAddress = "Email Address",
    phoneNumber = "Mobile Phone Number",
    cityRegion = "City / Region",
    password = "Password",
    selectBloodGroup = "Select Blood Group",
    volunteerForEmergency = "Volunteer for 24/7 emergency blood requests nearby",
    createDonorAccount = "Create Donor Account",
    signInToBloodSync = "Sign In to BloodSync",
    invalidEmailError = "Invalid email format! Please include a valid extension (e.g., name@gmail.com).",
    invalidPhoneError = "Invalid phone number! Must be a 10-digit number.",
    invalidNameError = "Please enter your full name (minimum 2 letters).",
    passwordMinLengthError = "Password must be at least 6 characters.",

    gender = "Gender",
    genderMale = "Male",
    genderFemale = "Female",
    age = "Age (Years)",
    agePlaceholder = "e.g. 18",
    minAgeHint = "Minimum registration age: 15 years",
    ageRestrictionError = "⚠️ Age Restriction: Minimum age required to register is 15 years old. You cannot register if you are under 15.",
    invalidAgeError = "Please enter a valid age (15 - 100 years).",

    chooseYourLanguage = "Choose Your Language",
    selectLanguageSubtitle = "Select your preferred language for BloodSync",
    continueButton = "Continue",
    englishLabel = "English",
    hindiLabel = "English",
    gujaratiLabel = "English",

    donorsDirectoryTitle = "Voluntary Donors Directory",
    searchDonorsPlaceholder = "Search donors by name, city, or blood group...",
    allBloodGroups = "All Groups",
    noDonorsFound = "No voluntary donors found",
    beTheFirstDonor = "Be the first lifesaver to register in your area!",
    chatOnWhatsApp = "WhatsApp Chat",
    callDonor = "Call Donor",
    availableNow = "Available Now",
    busyDonor = "Currently Busy",

    settingsTitle = "Settings",
    appearanceSection = "Appearance & Theme",
    lightMode = "Light Mode",
    darkMode = "Dark Mode",
    systemMode = "System Mode",
    languageSection = "Language",
    notificationSection = "Notification Controls",
    emergencyAlerts = "Emergency Blood Broadcasts",
    appointmentReminders = "Donation Reminders & Milestones",
    clinicalSafetySection = "Clinical Safety",
    dataManagementSection = "Data Management",
    clearCacheButton = "Clear Local Cache & Reset",
    appVersion = "BloodSync v2.6.0 • Production Build",

    donorProfileTitle = "Donor Profile",
    editProfile = "Edit Profile",
    totalDonations = "Donations",
    livesSaved = "Lives Saved",
    recoveryStatus = "Recovery",
    eligibleStatus = "Eligible",
    waitingDays = "Days Left",
    personalContactInfo = "Personal & Contact Information",
    availabilityNotifications = "Donor Availability & Alerts",
    bloodDonated = "Donated",
    availableForDonations = "Available for Emergency Donations",
    profileUpdatedSuccess = "Profile updated successfully!",

    exitAppTitle = "Exit BloodSync?",
    exitAppMessage = "Are you sure you want to close the app? You can stay to receive live blood donation and emergency alerts.",
    yesExit = "Yes, Exit",
    noStay = "No, Stay",

    newDonorRegisteredTitle = "🚨 New Donor Registered!",
    newDonorRegisteredBody = "has registered as an active voluntary donor."
)

val LocalAppStrings = staticCompositionLocalOf<TranslationStrings> { EnglishTranslations }
