package com.example.bloodsync_android.util

enum class AppLanguage(val code: String, val englishName: String, val nativeName: String) {
    ENGLISH("en", "English", "English"),
    HINDI("hi", "Hindi", "हिंदी"),
    GUJARATI("gu", "Gujarati", "ગુજરાતી")
}

data class TranslationStrings(
    // Common & Navigation
    val appName: String,
    val home: String,
    val donors: String,
    val appointments: String,
    val health: String,
    val profile: String,
    val settings: String,
    val notifications: String,
    val back: String,
    val close: String,
    val cancel: String,
    val confirm: String,
    val saveChanges: String,
    val signOut: String,

    // Home Screen
    val needBloodUrgently: String,
    val broadcastSosDesc: String,
    val requestBloodSos: String,
    val quickServices: String,
    val findDonorsTitle: String,
    val findDonorsDesc: String,
    val bloodBanksTitle: String,
    val bloodBanksDesc: String,
    val bookSlotTitle: String,
    val bookSlotDesc: String,
    val eligibleNow: String,
    val recoveryActive: String,

    // Auth Screen
    val signIn: String,
    val registerDonor: String,
    val continueWithGoogle: String,
    val fullName: String,
    val emailAddress: String,
    val phoneNumber: String,
    val cityRegion: String,
    val password: String,
    val selectBloodGroup: String,
    val volunteerForEmergency: String,
    val createDonorAccount: String,
    val signInToBloodSync: String,
    val invalidEmailError: String,
    val invalidPhoneError: String,
    val invalidNameError: String,
    val passwordMinLengthError: String,

    // Donors Directory
    val donorsDirectoryTitle: String,
    val searchDonorsPlaceholder: String,
    val allBloodGroups: String,
    val noDonorsFound: String,
    val beTheFirstDonor: String,
    val chatOnWhatsApp: String,
    val callDonor: String,
    val availableNow: String,
    val busyDonor: String,

    // Settings Screen
    val settingsTitle: String,
    val appearanceSection: String,
    val lightMode: String,
    val darkMode: String,
    val systemMode: String,
    val languageSection: String,
    val notificationSection: String,
    val emergencyAlerts: String,
    val appointmentReminders: String,
    val clinicalSafetySection: String,
    val dataManagementSection: String,
    val clearCacheButton: String,
    val appVersion: String,

    // Profile Screen
    val donorProfileTitle: String,
    val editProfile: String,
    val totalDonations: String,
    val livesSaved: String,
    val recoveryStatus: String,
    val eligibleStatus: String,
    val waitingDays: String,
    val personalContactInfo: String,
    val availabilityNotifications: String,

    // Notifications & Alerts
    val newDonorRegisteredTitle: String,
    val newDonorRegisteredBody: String
)

val EnglishTranslations = TranslationStrings(
    appName = "BloodSync",
    home = "Home",
    donors = "Donors",
    appointments = "Appointments",
    health = "Health",
    profile = "Profile",
    settings = "Settings",
    notifications = "Notifications",
    back = "Back",
    close = "Close",
    cancel = "Cancel",
    confirm = "Confirm",
    saveChanges = "Save Changes",
    signOut = "Sign Out",

    needBloodUrgently = "Need Blood Urgently?",
    broadcastSosDesc = "Broadcast an instant emergency SOS to all matching voluntary donors nearby.",
    requestBloodSos = "REQUEST BLOOD (1-TAP SOS)",
    quickServices = "Quick Services",
    findDonorsTitle = "Find Donors",
    findDonorsDesc = "Direct verified donors directory",
    bloodBanksTitle = "Blood Banks",
    bloodBanksDesc = "Real-time hospital reserves",
    bookSlotTitle = "Book Slot",
    bookSlotDesc = "Scheduled clinic donation",
    eligibleNow = "Eligible Now",
    recoveryActive = "Days Recovery Left",

    signIn = "Sign In",
    registerDonor = "Register Donor",
    continueWithGoogle = "Continue with Google",
    fullName = "Full Name",
    emailAddress = "Email Address",
    phoneNumber = "Mobile Phone Number",
    cityRegion = "City / Region",
    password = "Password",
    selectBloodGroup = "Select Blood Group",
    volunteerForEmergency = "Volunteer for 24/7 emergency blood requests nearby",
    createDonorAccount = "Create Donor Account",
    signInToBloodSync = "Sign In to BloodSync",
    invalidEmailError = "Invalid email format! Please include a valid extension (e.g., name@gmail.com).",
    invalidPhoneError = "Invalid phone number! Must be a 10-digit number.",
    invalidNameError = "Please enter your full name (minimum 2 letters).",
    passwordMinLengthError = "Password must be at least 6 characters.",

    donorsDirectoryTitle = "Voluntary Donors Directory",
    searchDonorsPlaceholder = "Search donors by name, city, or blood group...",
    allBloodGroups = "All Groups",
    noDonorsFound = "No voluntary donors found",
    beTheFirstDonor = "Be the first lifesaver to register in your area!",
    chatOnWhatsApp = "WhatsApp Chat",
    callDonor = "Call Donor",
    availableNow = "Available Now",
    busyDonor = "Currently Busy",

    settingsTitle = "Settings",
    appearanceSection = "Appearance & Theme",
    lightMode = "Light Mode",
    darkMode = "Dark Mode",
    systemMode = "System Mode",
    languageSection = "App Language / भाषा / ભાષા",
    notificationSection = "Notification Controls",
    emergencyAlerts = "Emergency Blood Broadcasts",
    appointmentReminders = "Donation Reminders & Milestones",
    clinicalSafetySection = "Clinical Safety",
    dataManagementSection = "Data Management",
    clearCacheButton = "Clear Local Cache & Reset",
    appVersion = "BloodSync v2.2.0 • Production Build",

    donorProfileTitle = "Donor Profile",
    editProfile = "Edit Profile",
    totalDonations = "Donations",
    livesSaved = "Lives Saved",
    recoveryStatus = "Recovery",
    eligibleStatus = "Eligible",
    waitingDays = "Days Left",
    personalContactInfo = "Personal & Contact Information",
    availabilityNotifications = "Donor Availability & Alerts",

    newDonorRegisteredTitle = "🚨 New Donor Registered!",
    newDonorRegisteredBody = "has registered as an active voluntary donor."
)

val HindiTranslations = TranslationStrings(
    appName = "ब्लडसिंक (BloodSync)",
    home = "होम",
    donors = "रक्तदाता",
    appointments = "अपॉइंटमेंट",
    health = "स्वास्थ्य",
    profile = "प्रोफाइल",
    settings = "सेटिंग्स",
    notifications = "सूचनाएं",
    back = "वापस",
    close = "बंद करें",
    cancel = "रद्द करें",
    confirm = "पुष्टि करें",
    saveChanges = "बदलाव सहेजें",
    signOut = "लॉग आउट",

    needBloodUrgently = "क्या तुरंत रक्त की आवश्यकता है?",
    broadcastSosDesc = "आस-पास के सभी योग्य स्वैच्छिक रक्तदाताओं को तुरंत आपातकालीन SOS संदेश भेजें।",
    requestBloodSos = "रक्त अनुरोध करें (1-टैप SOS)",
    quickServices = "त्वरित सेवाएं",
    findDonorsTitle = "रक्तदाता खोजें",
    findDonorsDesc = "सत्यापित रक्तदाता सूची",
    bloodBanksTitle = "ब्लड बैंक",
    bloodBanksDesc = "अस्पताल व ब्लड बैंक स्टॉक",
    bookSlotTitle = "स्लॉट बुक करें",
    bookSlotDesc = "रक्तदान के लिए समय चुनें",
    eligibleNow = "रक्तदान के लिए योग्य",
    recoveryActive = "दिन रिकवरी बाकी",

    signIn = "साइन इन",
    registerDonor = "रक्तदाता पंजीकरण",
    continueWithGoogle = "Google के साथ जारी रखें",
    fullName = "पूरा नाम",
    emailAddress = "ईमेल पता",
    phoneNumber = "मोबाइल फोन नंबर",
    cityRegion = "शहर / क्षेत्र",
    password = "पासवर्ड",
    selectBloodGroup = "रक्त समूह चुनें",
    volunteerForEmergency = "24/7 आपातकालीन रक्तदान अनुरोधों के लिए स्वेच्छा से जुड़ें",
    createDonorAccount = "रक्तदाता खाता बनाएं",
    signInToBloodSync = "BloodSync में साइन इन करें",
    invalidEmailError = "अमान्य ईमेल! कृपया सही एक्सटेंशन के साथ ईमेल दर्ज करें (उदा. name@gmail.com)।",
    invalidPhoneError = "अमान्य फोन नंबर! 10 अंकों का मान्य मोबाइल नंबर दर्ज करें।",
    invalidNameError = "कृपया अपना पूरा नाम दर्ज करें (कम से कम 2 अक्षर)।",
    passwordMinLengthError = "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",

    donorsDirectoryTitle = "स्वैच्छिक रक्तदाता सूची",
    searchDonorsPlaceholder = "नाम, शहर या रक्त समूह से खोजें...",
    allBloodGroups = "सभी ग्रुप",
    noDonorsFound = "कोई पंजीकृत रक्तदाता नहीं मिला",
    beTheFirstDonor = "अपने क्षेत्र में जीवन रक्षक बनने वाले पहले रक्तदाता बनें!",
    chatOnWhatsApp = "व्हाट्सएप चैट",
    callDonor = "कॉल करें",
    availableNow = "उपलब्ध",
    busyDonor = "वर्तमान में व्यस्त",

    settingsTitle = "सेटिंग्स",
    appearanceSection = "दिखावट और थीम",
    lightMode = "लाइट मोड",
    darkMode = "डार्क मोड",
    systemMode = "सिस्टम मोड",
    languageSection = "ऐप भाषा (Language / ભાષા)",
    notificationSection = "सूचना नियंत्रण",
    emergencyAlerts = "आपातकालीन रक्त प्रसारण",
    appointmentReminders = "रक्तदान रिमाइंडर और माइलस्टोन",
    clinicalSafetySection = "चिकित्सीय सुरक्षा (WHO 90-दिन)",
    dataManagementSection = "डेटा प्रबंधन",
    clearCacheButton = "लोकल कैश साफ़ करें और रीसेट करें",
    appVersion = "BloodSync v2.2.0 • सुरक्षित संस्करण",

    donorProfileTitle = "रक्तदाता प्रोफाइल",
    editProfile = "प्रोफाइल संपादित करें",
    totalDonations = "कुल रक्तदान",
    livesSaved = "बचाए गए जीवन",
    recoveryStatus = "रिकवरी",
    eligibleStatus = "योग्य",
    waitingDays = "दिन शेष",
    personalContactInfo = "व्यक्तिगत और संपर्क जानकारी",
    availabilityNotifications = "रक्तदाता उपलब्धता और अलर्ट",

    newDonorRegisteredTitle = "🚨 नया रक्तदाता पंजीकृत हुआ!",
    newDonorRegisteredBody = "एक सक्रिय स्वैच्छिक रक्तदाता के रूप में पंजीकृत हुए हैं।"
)

val GujaratiTranslations = TranslationStrings(
    appName = "બ્લડસિંક (BloodSync)",
    home = "હોમ",
    donors = "દાતાઓ",
    appointments = "મુલાકાત",
    health = "સ્વાસ્થ્ય",
    profile = "પ્રોફાઇલ",
    settings = "સેટિંગ્સ",
    notifications = "સૂચનાઓ",
    back = "પાછળ",
    close = "બંધ કરો",
    cancel = "રદ કરો",
    confirm = "પુષ્ટિ કરો",
    saveChanges = "ફેરફારો સાચવો",
    signOut = "લૉગ આઉટ",

    needBloodUrgently = "શું તાત્કાલિક લોહીની જરૂર છે?",
    broadcastSosDesc = "નજીકના તમામ સુસંગત સ્વૈચ્છિક રક્તદાતાઓને તાત્કાલિક કટોકટી SOS સંદેશ મોકલો.",
    requestBloodSos = "લોહીની વિનંતી કરો (1-ટેપ SOS)",
    quickServices = "ઝડપી સેવાઓ",
    findDonorsTitle = "દાતાઓ શોધો",
    findDonorsDesc = "ચકાસાયેલ રક્તદાતાઓની યાદી",
    bloodBanksTitle = "બ્લડ બેંકો",
    bloodBanksDesc = "હોસ્પિટલ અને બ્લડ બેંક સ્ટોક",
    bookSlotTitle = "સ્લોટ બુક કરો",
    bookSlotDesc = "રક્તદાન માટે સમય પસંદ કરો",
    eligibleNow = "રક્તદાન માટે યોગ્ય",
    recoveryActive = "દિવસ રિકવરી બાકી",

    signIn = "સાઇન ઇન",
    registerDonor = "દાતા નોંધણી",
    continueWithGoogle = "Google સાથે ચાલુ રાખો",
    fullName = "પૂરું નામ",
    emailAddress = "ઇમેઇલ સરનામું",
    phoneNumber = "મોબાઇલ ફોન નંબર",
    cityRegion = "શહેર / વિસ્તાર",
    password = "પાસવર્ડ",
    selectBloodGroup = "બ્લડ ગ્રૂપ પસંદ કરો",
    volunteerForEmergency = "24/7 કટોકટી રક્તદાન વિનંતીઓ માટે સ્વેચ્છાએ જોડાઓ",
    createDonorAccount = "દાતા એકાઉન્ટ બનાવો",
    signInToBloodSync = "BloodSync માં સાઇન ઇન કરો",
    invalidEmailError = "અમાન્ય ઇમેઇલ! કૃપા કરીને માન્ય એક્સ્ટેંશન સાથે ઇમેઇલ દાખલ કરો (દા.ત. name@gmail.com).",
    invalidPhoneError = "અમાન્ય ફોન નંબર! 10 અંકનો માન્ય મોબાઇલ નંબર દાખલ કરો.",
    invalidNameError = "કૃપા કરીને તમારું પૂરું નામ દાખલ કરો (ઓછામાં ઓછા 2 અક્ષરો).",
    passwordMinLengthError = "પાસવર્ડ ઓછામાં ઓછો 6 અક્ષરોનો હોવો જોઈએ.",

    donorsDirectoryTitle = "સ્વૈચ્છિક રક્તદાતાઓની યાદી",
    searchDonorsPlaceholder = "નામ, શહેર અથવા બ્લડ ગ્રૂપથી શોધો...",
    allBloodGroups = "બધા ગ્રૂપ",
    noDonorsFound = "કોઈ નોંધાયેલા રક્તદાતા મળ્યા નથી",
    beTheFirstDonor = "તમારા વિસ્તારમાં જીવનદાતા બનનાર પ્રથમ રક્તદાતા બનો!",
    chatOnWhatsApp = "WhatsApp ચેટ",
    callDonor = "કૉલ કરો",
    availableNow = "ઉપલબ્ધ",
    busyDonor = "હાલમાં વ્યસ્ત",

    settingsTitle = "સેટિંગ્સ",
    appearanceSection = "દેખાવ અને થીમ",
    lightMode = "લાઇટ મોડ",
    darkMode = "ડાર્ક મોડ",
    systemMode = "સિસ્ટમ મોડ",
    languageSection = "એપ્લિકેશન ભાષા (Language / भाषा)",
    notificationSection = "સૂચના નિયંત્રણો",
    emergencyAlerts = "કટોકટી રક્ત પ્રસારણ",
    appointmentReminders = "રક્તદાન રીમાઇન્ડર અને પ્રમાણપત્ર",
    clinicalSafetySection = "તબીબી સલામતી (WHO 90-દિવસ)",
    dataManagementSection = "ડેટા મેનેજમેન્ટ",
    clearCacheButton = "લોકલ કેશ સાફ કરો અને રીસેટ કરો",
    appVersion = "BloodSync v2.2.0 • ઉત્પાદન સંસ્કરણ",

    donorProfileTitle = "દાતા પ્રોફાઇલ",
    editProfile = "પ્રોફાઇલ સંપાદિત કરો",
    totalDonations = "કુલ રક્તદાન",
    livesSaved = "બચાવેલ જીવન",
    recoveryStatus = "રિકવરી",
    eligibleStatus = "યોગ્ય",
    waitingDays = "દિવસ બાકી",
    personalContactInfo = "વ્યક્તિગત અને સંપર્ક માહિતી",
    availabilityNotifications = "દાતા ઉપલબ્ધતા અને સૂચનાઓ",

    newDonorRegisteredTitle = "🚨 નવો રક્તદાતા નોંધાયો!",
    newDonorRegisteredBody = "એક સક્રિય સ્વૈચ્છિક રક્તદાતા તરીકે નોંધાયા છે."
)

object LanguageManager {
    fun getStrings(language: AppLanguage): TranslationStrings = when (language) {
        AppLanguage.ENGLISH -> EnglishTranslations
        AppLanguage.HINDI -> HindiTranslations
        AppLanguage.GUJARATI -> GujaratiTranslations
    }
}
