/**
 * BloodSync Backend - System Constants & Error Categories
 */

const ERROR_CATEGORIES = {
  OTP_GENERATION_ERROR: 'OTP_GENERATION_ERROR',
  OTP_DATABASE_ERROR: 'OTP_DATABASE_ERROR',
  EMAIL_CONFIGURATION_ERROR: 'EMAIL_CONFIGURATION_ERROR',
  SMTP_AUTH_ERROR: 'SMTP_AUTH_ERROR',
  EMAIL_SEND_ERROR: 'EMAIL_SEND_ERROR',
  FIREBASE_ERROR: 'FIREBASE_ERROR',
  RATE_LIMIT_ERROR: 'RATE_LIMIT_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};

const REQUEST_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
};

const OTP_GEN_STATUS = {
  GENERATED: 'GENERATED',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED',
};

const EMAIL_SEND_STATUS = {
  SENT: 'SENT',
  FAILED: 'FAILED',
  PENDING: 'PENDING',
};

const FIRESTORE_COLLECTIONS = {
  BACKEND_DEBUGGER_LOGS: 'backend_debugger_logs',
  OTP_VERIFICATIONS: 'otp_verifications',
  OTP_RATE_LIMITS: 'otp_rate_limits',
  CRITICAL_ALERTS: 'critical_alerts',
  USERS: 'users',
};

const CONFIG_DEFAULTS = {
  OTP_LENGTH: 6,
  OTP_EXPIRY_MINUTES: 5,
  OTP_MAX_ATTEMPTS: 5,
  RATE_LIMIT_WINDOW_MINUTES: 10,
  RATE_LIMIT_MAX_REQUESTS: 3,
  RATE_LIMIT_COOLDOWN_SECONDS: 60,
};

module.exports = {
  ERROR_CATEGORIES,
  REQUEST_STATUS,
  OTP_GEN_STATUS,
  EMAIL_SEND_STATUS,
  FIRESTORE_COLLECTIONS,
  CONFIG_DEFAULTS,
};
